### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Niketats** [luaxlab/ll-fabric-quilt#13]
`org.quiltmc.loader.impl.FormattedException: java.lang.NullPointerException: Registry Object not present: littlelogistics:tug
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:519)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.NullPointerException: Registry Object not present: littlelogistics:tug
	at java.base/java.util.Objects.requireNonNull(Objects.java:334)
	at io.github.fabricators_of_create.porting_lib.util.RegistryObject.get(RegistryObject.java:66)
	at de.luaxlab.shipping.common.core.ModEntities.register(ModEntities.java:128)
	at de.luaxlab.shipping.common.core.Registration.register(Registration.java:49)
	at de.luaxlab.shipping.common.core.ModCommon.onInitialize(ModCommon.java:43)
	at net.minecraft.class_2966.handler$ehe001$quilt_base$onInitialize(class_2966.java:1042)
	at net.minecraft.class_2966.method_12851(class_2966.java:69)
	at net.minecraft.client.main.Main.method_44604(Main.java:161)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:517)
	... 2 more
`

**Comment by luaxlab** [comment]
Before opening a issue please watch out for similar issues. This one looks similar to #12 

Please provide more information (full game log)
